[build]
  publish = "dist"
  command = "npm ci && npm run build"
  environment = { NODE_VERSION = "20", NODE_ENV = "production", SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}", SUPABASE_URL = "${SUPABASE_URL}" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
