[build]
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 3000

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
