// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekneusrruxypjyhgviwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbmV1c3JydXh5cGp5aGd2aXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NDY5NzYsImV4cCI6MjA1MTEyMjk3Nn0.Ser9EC-E6YxpbwlmJ1awR2hStf7GHFAj5KIOvusu1P0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
